
- name: Install rpm key
  rpm_key: 
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install logstash
  yum:
    name: logstash
    state: present

- name: Start logstash
  systemd:
    name: elasticsearch
    state: started
    enabled: yes  
