
- name: Install rpm key
  rpm_key: 
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install kibana
  yum:
    name: kibana
    state: present

- name: Start kibana
  systemd:
    name: kibana
    state: started
    enabled: yes  
