
- name: Install rpm key
  rpm_key: 
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo


- name: Install elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Start elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes  
